name       : tensorflow
version    : 2.10.1
release    : 23
source     :
    - https://github.com/tensorflow/tensorflow/archive/refs/tags/v2.10.1.tar.gz : 622a92e22e6f3f4300ea43b3025a0b6122f1cc0e2d9233235e4c628c331a94a3
license    : Apache-2.0
component  :
    - programming.python
    - c-api : programming.library
summary    :
    - An open source machine learning framework for high performance numerical computation
    - c-api : The C API for tensorflow
description: |
    TensorFlow™ is an open source software library for high performance numerical computation using data flow graphs.
networking : yes
debug      : no
ccache     : no
patterns   :
    - c-api :
        - /usr/include
        - /usr/lib/lib*.so*
        - /usr/lib64
builddeps  :
    - pkgconfig(hwloc)
    - pkgconfig(icu-i18n)
    - pkgconfig(jsoncpp)
    - pkgconfig(libcares)
    - pkgconfig(libcurl)
    - pkgconfig(libjpeg)
    - pkgconfig(libpcre)
    - pkgconfig(libpng)
    - pkgconfig(protobuf)
    - pkgconfig(python3)
    - pkgconfig(re2)
    - pkgconfig(sqlite3)
    - abseil-cpp-devel
    - bazel
    - cython
    - double-conversion-devel
    - giflib-devel
    - git
    - llvm-clang-devel
    - lmdb-devel
    - nasm
    - pybind11
    - python-absl-py
    - python-astor
    - python-gast
    - python-keras-applications
    - python-keras-preprocessing
    - python-packaging
    - python-protobuf
    - python-requests
    - python-six
    - python-termcolor
    - python-typing-extensions
    - python-wheel
    - python-wrapt
    - snappy-devel
rundeps    :
    - python-astor
    - python-astunparse
    - python-flatbuffers
    - python-gast
    - python-keras-applications
    - python-keras-preprocessing
    - python-mock
    - python-opt-einsum
    - python-tensorboard
    - python-termcolor
    - python-typing-extensions
    - python-wrapt
    - pybind11
clang      : yes
environment: |
    export CC_OPT_FLAGS="-mtune=generic -march=x86-64 -g2 -O3"
    export PYTHON_BIN_PATH=/usr/bin/python3
    export TF_DOWNLOAD_CLANG=0
    export TF_ENABLE_XLA=0
    export TF_IGNORE_MAX_BAZEL_VERSION=1
    export TF_NEED_CUDA=0
    export TF_NEED_OPENCL_SYCL=0
    export TF_NEED_ROCM=0
    export TF_ENABLE_MLIR=0
    export TF_SET_ANDROID_WORKSPACE=0
    export TF_SYSTEM_LIBS="absl_py astor_archive com_google_protobuf curl cython double_conversion functools32_archive gast_archive gif hwloc libjpeg_turbo icu jsoncpp_git lmdb nasm org_sqlite png pybind11 six_archive snappy termcolor_archive typing_extensions_archive wrapt zlib"
    export USE_DEFAULT_PYTHON_LIB_PATH=1
setup      : |
    ./configure
build      : |
    # https://github.com/bazelbuild/bazel/issues/15359
    bazel build \
        --config=opt \
        --config=noaws  --config=nogcp --config=nohdfs --config=nonccl \
        --spawn_strategy=sandboxed \
        //tensorflow/tools/lib_package:libtensorflow \
        //tensorflow/tools/pip_package:build_pip_package
    mkdir -p tmp
    bazel-bin/tensorflow/tools/pip_package/build_pip_package $workdir/tmp/tensorflow_pkg
    bazel shutdown
install    : |
    WHEEL_NAME=$(basename tmp/tensorflow_pkg/tensorflow*.whl)
    python3 -m pip install --no-deps --root=$installdir tmp/tensorflow_pkg/$WHEEL_NAME

    # Remove tensorboard
    rm -rfv $installdir/usr/bin/tensorboard

    # tensorflow-c-api
    tensorflow/c/generate-pc.sh --prefix=%PREFIX% --libdir=lib%LIBSUFFIX% --version=$version
    install -Dm00644 tensorflow.pc $installdir/%libdir%/pkgconfig/tensorflow.pc
    tar -zxvf bazel-bin/tensorflow/tools/lib_package/libtensorflow.tar.gz -C $installdir/%PREFIX%
    rm -rfv $installdir/%PREFIX%/{LICENSE,THIRD_PARTY_TF_C_LICENSES}
