name       : tensorflow
version    : 2.1.0
release    : 12
source     :
    - https://github.com/tensorflow/tensorflow/archive/v2.1.0.tar.gz : 638e541a4981f52c69da4a311815f1e7989bf1d67a41d204511966e1daed14f7
license    : Apache-2.0
component  :
    - programming.python
    - c-api : programming.library
summary    :
    - An open source machine learning framework for high performance numerical computation
    - c-api : The C API for tensorflow
description: |
    TensorFlow™ is an open source software library for high performance numerical computation using data flow graphs.
networking : yes
debug      : no
patterns   :
    - c-api :
        - /usr/include
        - /usr/lib/lib*.so*
        - /usr/lib64
builddeps  :
    - pkgconfig(hwloc)
    - pkgconfig(icu-i18n)
    - pkgconfig(jsoncpp)
    - pkgconfig(libcares)
    - pkgconfig(libcurl)
    - pkgconfig(libjpeg)
    - pkgconfig(libpcre)
    - pkgconfig(libpng)
    - pkgconfig(protobuf)
    - pkgconfig(python3)
    - pkgconfig(sqlite3)
    - bazel
    - cython
    - double-conversion-devel
    - flatbuffers-devel
    - giflib-devel
    - git
    - lmdb-devel
    - nasm
    - python-absl-py
    - python-astor
    - python-gast
    - python-keras-applications
    - python-keras-preprocessing
    - python-protobuf
    - python-six
    - python-termcolor
    - python-wheel
    - python-wrapt
    - re2-devel
    - snappy-devel
rundeps    :
    - python-absl-py
    - python-astor
    - python-gast
    - python-keras-applications
    - python-keras-preprocessing
    - python-mock
    - python-opt-einsum
    - python-tensorboard
    - python-termcolor
    - python-wrapt
clang      : yes
environment: |
    export CC_OPT_FLAGS="-mtune=generic -march=x86-64 -g2 -O3"
    export PYTHON_BIN_PATH=/usr/bin/python3
    export TF_DOWNLOAD_CLANG=0
    export TF_ENABLE_XLA=0
    export TF_IGNORE_MAX_BAZEL_VERSION=1
    export TF_NEED_CUDA=0
    export TF_NEED_OPENCL_SYCL=0
    export TF_NEED_ROCM=0
    export TF_SET_ANDROID_WORKSPACE=0
    export TF_SYSTEM_LIBS="absl_py astor_archive com_google_protobuf com_googlesource_code_re2 curl cython double_conversion enum34_archive flatbuffers functools32_archive gast_archive gif hwloc icu jpeg jsoncpp_git keras_applications_archive lmdb nasm org_sqlite pcre png six_archive snappy termcolor_archive wrapt zlib_archive"
    export USE_DEFAULT_PYTHON_LIB_PATH=1
setup      : |
    %patch -p1 < $pkgfiles/fix_systemlib_build.patch
    %patch -p1 < $pkgfiles/add_grpc_fix_for_gettid.patch
    ./configure
build      : |
    bazel build \
        --config=opt \
        --config=noaws  --config=nogcp --config=nohdfs --config=nonccl \
        //tensorflow/tools/lib_package:libtensorflow //tensorflow/tools/pip_package:build_pip_package
    mkdir -p tmp
    bazel-bin/tensorflow/tools/pip_package/build_pip_package tmp/tensorflow_pkg
install    : |
    WHEEL_NAME=$(basename tmp/tensorflow_pkg/tensorflow*.whl)
    pip3 install --no-deps --root=$installdir tmp/tensorflow_pkg/$WHEEL_NAME

    # Remove tensorboard
    rm -rfv $installdir/usr/bin/tensorboard

    # tensorflow-c-api
    tensorflow/c/generate-pc.sh --prefix=%PREFIX% --libdir=lib%LIBSUFFIX% --version=$version
    install -Dm00644 tensorflow.pc $installdir/%libdir%/pkgconfig/tensorflow.pc
    tar -zxvf bazel-bin/tensorflow/tools/lib_package/libtensorflow.tar.gz -C $installdir/%PREFIX%
    rm -rfv $installdir/%PREFIX%/{LICENSE,THIRD_PARTY_TF_C_LICENSES}
