name       : tensorflow
version    : 1.14.0
release    : 3
source     :
    - https://github.com/tensorflow/tensorflow/archive/v1.14.0.tar.gz : aa2a6a1daafa3af66807cfe0bc77bfe1144a9a53df9a96bab52e3e575b3047ed
license    : Apache-2.0
component  :
    - programming.python
    - c-api : programming.library
summary    :
    - An open source machine learning framework for high performance numerical computation
    - c-api : The C API for tensorflow
description: |
    TensorFlow™ is an open source software library for high performance numerical computation using data flow graphs.
networking : yes
debug      : no
patterns   :
    - c-api :
        - /usr/include
        - /usr/lib/lib*.so*
        - /usr/lib64
builddeps  :
    - pkgconfig(libcares)
    - pkgconfig(python3)
    - bazel
    - python-keras-applications
    - python-keras-preprocessing
    - python-wheel
rundeps    :
    - python-absl-py
    - python-astor
    - python-gast
    - python-keras-applications
    - python-keras-preprocessing
    - python-mock
    - python-tensorboard
setup      : |
    cp -a $workdir $PKG_BUILD_DIR/py3build

    export USE_DEFAULT_PYTHON_LIB_PATH=1
    export TF_ENABLE_XLA=1
    export TF_NEED_OPENCL_SYCL=0
    export TF_NEED_ROCM=0
    export TF_NEED_CUDA=0
    export TF_DOWNLOAD_CLANG=0
    export TF_NEED_MPI=0
    export CC_OPT_FLAGS="-mtune=generic -march=x86-64 -g2 -O3"
    export TF_SET_ANDROID_WORKSPACE=0

    pushd $PKG_BUILD_DIR/py3build
    export PYTHON_BIN_PATH=/usr/bin/python3
    mkdir -p $PKG_BUILD_DIR/bazel-cache-py3build
    TEST_TMPDIR=$PKG_BUILD_DIR/bazel-cache-py3build ./configure
    popd
build      : |
    pushd $PKG_BUILD_DIR/py3build
    TEST_TMPDIR=$PKG_BUILD_DIR/bazel-cache-py3build bazel build \
        --config=opt \
        --config=noaws --config=nogcp \
        --config=noignite --config=nokafka \
        //tensorflow/tools/lib_package:libtensorflow //tensorflow/tools/pip_package:build_pip_package
    mkdir -p tmp
    bazel-bin/tensorflow/tools/pip_package/build_pip_package tmp/tensorflow_pkg
    popd
install    : |
    pushd $PKG_BUILD_DIR/py3build
    WHEEL_NAME=$(basename tmp/tensorflow_pkg/tensorflow*.whl)
    pip3 install --no-deps --root=$installdir tmp/tensorflow_pkg/$WHEEL_NAME

    # Remove tensorboard
    rm -rfv $installdir/usr/bin/tensorboard

    # tensorflow-c-api
    tensorflow/c/generate-pc.sh --prefix=%PREFIX% --libdir=lib%LIBSUFFIX% --version=$version
    install -Dm00644 tensorflow.pc $installdir/%libdir%/pkgconfig/tensorflow.pc
    tar -zxvf bazel-bin/tensorflow/tools/lib_package/libtensorflow.tar.gz -C $installdir/%PREFIX%
    popd
